# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY ./app .

# Run tests using pytest when the container starts
CMD ["sh", "-c", "PYTHONPATH=/app pytest --maxfail=1 --disable-warnings -q"]